### ISSUE TITLE
bug(subcommands): subcommands wrongfully emits to `MessageCommandError` instead of `MessageSubcommandError`

### ISSUE THREAD

**Issue by camdzic** [sapphiredev/plugins#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Subcommands emit "MessageCommandError" instead of "MessageSubcommandError" when error occurs

### Steps To Reproduce

Simply create a subcommand, don't enter anything and see what event it emits

### Expected behavior

If "MessageSubcommandNoMatch" is emitted then it should be in subcommands events and not regular

### Screenshots

![Code_cIj7t4CgDI](https://github.com/user-attachments/assets/ece6727c-ffc4-4fc6-a48b-2260b7c00e00)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 3.40GHz
    Memory: 2.63 GB / 7.96 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD      
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD       
    pnpm: 9.6.0 - ~\AppData\Roaming\npm\pnpm.CMD
```

**Comment by camdzic** [comment]
**Update:** 
In the subcommand code, a UserError is thrown for what I am saying, which makes no sense because it will trigger an ordinary MessageCommandError.
[line 334](https://github.com/sapphiredev/plugins/blob/main/packages/subcommands/src/lib/Subcommand.ts)

**Comment by camdzic** [comment]
Also, one problem is that when I use message subcommands with arguments and don't enter an argument, MessageSubcommandError is emitted instead of the normal one, and when the subcommand fails, a normal event is emitted.

**Comment by favna** [comment]
I'll be adding new events `SubcommandPluginEvents.ChatInputSubcommandNoMatchError` and `SubcommandPluginEvents.MessageSubcommandNoMatchError` as replacements for the emit to `ChatInputCommandError` and `MessageCommandError` respectively, because the payload that we sent the error event will never match with the data that is available when matching a subcommand and we follow a strict pattern of only 1 payload structure per listener in order for the payload to be strictly typed (TypeScript first and all that)
